hw_fence: Fix -Wimplicit-int
techpack/mm/hw_fence/src/hw_fence_drv_priv.c:137:15: error: type
specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
static inline _lock_client_queue(int queue_type)
~~~~~~~~~~~~~ ^
int
1 error generated.

Signed-off-by: Pavel Dubrova <pashadubrova@gmail.com>